# Generated by Django 3.1.6 on 2021-07-01 22:01

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210417_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
