# Generated by Django 3.1.6 on 2021-07-03 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210702_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholar',
            old_name='body',
            new_name='content',
        ),
    ]
