# Generated by Django 3.1.6 on 2021-07-03 01:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210702_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
